import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import aos from "aos";

import {
  Header,
  Hero,
  Features,
  Services,
  Schedule,
  Monitor,
  Pricing,
  Support,
  Clients,
  Subscribe,
  Footer,
} from "../components";

const Home: NextPage = () => {
  useEffect(() => {
    aos.init({ easing: "ease-in-out" });
  }, []);

  return (
    <div className="bg-white overflow-hidden">
      <Head>
        <title>Digital Agency - Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="description"
          content="Landing Page by AR Shakir in Dribbble"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Hero */}
      <div className="py-10 px-16 w-full h-screen hero-container">
        <Header />
        <Hero />
      </div>

      <Features />

      <Services />

      <Schedule />

      <Monitor />

      <Pricing />

      <Support />

      <Clients />

      <div className="w-full flex items-center justify-center mb-16">
        <div className="w-3/4 ring-1 ring-gray-100"></div>
      </div>

      <Subscribe />

      <Footer />
    </div>
  );
};

export default Home;
