import { useCallback, useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import aos from "aos";
import { Header, Hero } from "../components";

const Home: NextPage = () => {
  const [theme, setTheme] = useState("");

  useEffect(() => {
    setTheme(localStorage.getItem("theme") || "light");
    aos.init({ easing: "ease-in-out-quart" });
  }, []);

  const handleSwitchTheme = () => {
    if (theme === "light") {
      setTheme("dark");
      return;
    }

    setTheme("light");
  };

  useEffect(() => {
    const html = window.document.documentElement;

    if (theme) {
      if (theme === "dark") {
        html.classList.add(theme);
        html.classList.remove("light");
        localStorage.setItem("theme", theme);
        return;
      }

      html.classList.add(theme);
      html.classList.remove("dark");
      localStorage.setItem("theme", theme);
    }
  }, [theme]);

  return (
    <div className={`bg-[#f6f1ec] dark:bg-slate-700 h-screen w-screen`}>
      <Head>
        <title>Selecto - Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="description"
          content="Landing Page by Daniel Sun from dribbble.com"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header theme={theme} handleSwitchTheme={handleSwitchTheme} />
      <Hero />
    </div>
  );
};

export default Home;
