import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import aos from "aos";

import { Header, Hero } from "../components";

const Home: NextPage = () => {
  useEffect(() => {
    aos.init({ easing: "ease-in-out-quad" });
  }, []);

  return (
    <div className="px-12 w-screen h-screen bg-[#fdf7f2] overflow-hidden">
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />
    </div>
  );
};

export default Home;
