import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import aos from "aos";
import { Header, Hero, Marquee } from "../components";

const Home: NextPage = () => {
  useEffect(() => {
    aos.init({ easing: "ease-in-out-quart" });
  }, []);

  return (
    <div className="overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Marquee />
      <Hero />
    </div>
  );
};

export default Home;
