import type { NextPage } from "next";
import Head from "next/head";
import aos from "aos";

import {
  Benefits,
  Clients,
  ContactUs,
  Footer,
  Header,
  Hero,
  SEOSpread,
  TeamBenefits,
  Traffics,
} from "../components";
import { useEffect } from "react";

const Home: NextPage = () => {
  useEffect(() => {
    aos.init({ easing: "ease-in-out-quad" });
  }, []);

  return (
    <div className="overflow-x-hidden">
      <Head>
        <title>Meta - Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="description"
          content="Landing Page from Dribbble by Sajib Rahman"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className="px-36">
        <Hero />
        <Benefits />
        <SEOSpread />
      </div>

      <Clients />
      <Traffics />
      <TeamBenefits />
      <Footer />
    </div>
  );
};

export default Home;
